services:
  - type: web
    name: 22logistics-api
    env: node
    region: oregon
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node dist/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false        # you'll paste this manually in dashboard
      - key: JWT_SECRET
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: BASE_URL
        sync: false