/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceCharterRouteImport } from './routes/service-charter'
import { Route as SchedulingPolicyRouteImport } from './routes/scheduling-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingDisclosureRouteImport } from './routes/pricing-disclosure'
import { Route as PlatformPolicyRouteImport } from './routes/platform-policy'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as DriverConductRouteImport } from './routes/driver-conduct'
import { Route as CustomerRightsRouteImport } from './routes/customer-rights'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessAccountRouteImport } from './routes/business-account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceCharterRoute = ServiceCharterRouteImport.update({
  id: '/service-charter',
  path: '/service-charter',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingPolicyRoute = SchedulingPolicyRouteImport.update({
  id: '/scheduling-policy',
  path: '/scheduling-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingDisclosureRoute = PricingDisclosureRouteImport.update({
  id: '/pricing-disclosure',
  path: '/pricing-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformPolicyRoute = PlatformPolicyRouteImport.update({
  id: '/platform-policy',
  path: '/platform-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverConductRoute = DriverConductRouteImport.update({
  id: '/driver-conduct',
  path: '/driver-conduct',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRightsRoute = CustomerRightsRouteImport.update({
  id: '/customer-rights',
  path: '/customer-rights',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAccountRoute = BusinessAccountRouteImport.update({
  id: '/business-account',
  path: '/business-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-account': typeof BusinessAccountRoute
  '/contact': typeof ContactRoute
  '/customer-rights': typeof CustomerRightsRoute
  '/driver-conduct': typeof DriverConductRoute
  '/faqs': typeof FaqsRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/platform-policy': typeof PlatformPolicyRoute
  '/pricing-disclosure': typeof PricingDisclosureRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/scheduling-policy': typeof SchedulingPolicyRoute
  '/service-charter': typeof ServiceCharterRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-account': typeof BusinessAccountRoute
  '/contact': typeof ContactRoute
  '/customer-rights': typeof CustomerRightsRoute
  '/driver-conduct': typeof DriverConductRoute
  '/faqs': typeof FaqsRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/platform-policy': typeof PlatformPolicyRoute
  '/pricing-disclosure': typeof PricingDisclosureRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/scheduling-policy': typeof SchedulingPolicyRoute
  '/service-charter': typeof ServiceCharterRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-account': typeof BusinessAccountRoute
  '/contact': typeof ContactRoute
  '/customer-rights': typeof CustomerRightsRoute
  '/driver-conduct': typeof DriverConductRoute
  '/faqs': typeof FaqsRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/platform-policy': typeof PlatformPolicyRoute
  '/pricing-disclosure': typeof PricingDisclosureRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/scheduling-policy': typeof SchedulingPolicyRoute
  '/service-charter': typeof ServiceCharterRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business-account'
    | '/contact'
    | '/customer-rights'
    | '/driver-conduct'
    | '/faqs'
    | '/features'
    | '/how-it-works'
    | '/platform-policy'
    | '/pricing-disclosure'
    | '/privacy'
    | '/refund-policy'
    | '/scheduling-policy'
    | '/service-charter'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business-account'
    | '/contact'
    | '/customer-rights'
    | '/driver-conduct'
    | '/faqs'
    | '/features'
    | '/how-it-works'
    | '/platform-policy'
    | '/pricing-disclosure'
    | '/privacy'
    | '/refund-policy'
    | '/scheduling-policy'
    | '/service-charter'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/business-account'
    | '/contact'
    | '/customer-rights'
    | '/driver-conduct'
    | '/faqs'
    | '/features'
    | '/how-it-works'
    | '/platform-policy'
    | '/pricing-disclosure'
    | '/privacy'
    | '/refund-policy'
    | '/scheduling-policy'
    | '/service-charter'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessAccountRoute: typeof BusinessAccountRoute
  ContactRoute: typeof ContactRoute
  CustomerRightsRoute: typeof CustomerRightsRoute
  DriverConductRoute: typeof DriverConductRoute
  FaqsRoute: typeof FaqsRoute
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PlatformPolicyRoute: typeof PlatformPolicyRoute
  PricingDisclosureRoute: typeof PricingDisclosureRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SchedulingPolicyRoute: typeof SchedulingPolicyRoute
  ServiceCharterRoute: typeof ServiceCharterRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-charter': {
      id: '/service-charter'
      path: '/service-charter'
      fullPath: '/service-charter'
      preLoaderRoute: typeof ServiceCharterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling-policy': {
      id: '/scheduling-policy'
      path: '/scheduling-policy'
      fullPath: '/scheduling-policy'
      preLoaderRoute: typeof SchedulingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing-disclosure': {
      id: '/pricing-disclosure'
      path: '/pricing-disclosure'
      fullPath: '/pricing-disclosure'
      preLoaderRoute: typeof PricingDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-policy': {
      id: '/platform-policy'
      path: '/platform-policy'
      fullPath: '/platform-policy'
      preLoaderRoute: typeof PlatformPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-conduct': {
      id: '/driver-conduct'
      path: '/driver-conduct'
      fullPath: '/driver-conduct'
      preLoaderRoute: typeof DriverConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-rights': {
      id: '/customer-rights'
      path: '/customer-rights'
      fullPath: '/customer-rights'
      preLoaderRoute: typeof CustomerRightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-account': {
      id: '/business-account'
      path: '/business-account'
      fullPath: '/business-account'
      preLoaderRoute: typeof BusinessAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessAccountRoute: BusinessAccountRoute,
  ContactRoute: ContactRoute,
  CustomerRightsRoute: CustomerRightsRoute,
  DriverConductRoute: DriverConductRoute,
  FaqsRoute: FaqsRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  PlatformPolicyRoute: PlatformPolicyRoute,
  PricingDisclosureRoute: PricingDisclosureRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SchedulingPolicyRoute: SchedulingPolicyRoute,
  ServiceCharterRoute: ServiceCharterRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
